$(document).ready(function(){          
		$('#header__icon').click(function(e){            
			e.preventDefault();            
			$('body').toggleClass('with--sidebar');        
		});        
		$('#site-cache').click(function(e){      
			$('body').removeClass('with--sidebar');    
		});
		$('.dropbtn').click(function(){
			document.getElementById("myDropdown").classList.toggle("show");
		})   
});